In [3]:
import numpy as np

In [4]:
a = np.array([5,7,8])
a

array([5, 7, 8])

In [5]:
a.shape   #3 dimension

(3,)

In [6]:
b = np.array([[5,7,8], [7,3,4]])
b

array([[5, 7, 8],
       [7, 3, 4]])

In [7]:
k = np.array([[3,8,4], [9,3,5], [11,15,17], [19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [8]:
k.shape

(4, 3)

In [61]:
m = np.array([[[4,41],[8,81],[7,71]], 
              [[3,31],[1,11],[5,51]], 
              [[6,61,],[9,91],[13,131]]
              ])    #3d array matrix
m
#m.shape

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [18]:
m.shape

(3, 3, 2)

In [20]:
k

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [27]:
#k[2]  # have some limitations as a particular vertical colm can't be accessed so prefer mixing w slicing
k[2,0:3:1] #subscripting along with slicing  
#k[2,0:] , k[2, :3], k[2,:]

array([11, 15, 17])

In [24]:
m[1,0,0]    ##subscripting :another method to acess apart from indexing and slicing

3

In [32]:
k[:,1]   # won't maintain dimension so everything in slicing
k[:,1:2]  

array([[ 8],
       [ 3],
       [15],
       [31]])

In [33]:
m

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [49]:
m[:2,1:3,:1]   
m[:2, -2:, :1]

array([[[8],
        [7]],

       [[1],
        [5]]])

In [59]:
m[2:, 1:3, ]
m[-1:, -2:, :]

array([[[  9,  91],
        [ 13, 131]]])

In [62]:
b

array([[5, 7, 8],
       [7, 3, 4]])

In [63]:
b[0,0] = 505
b

array([[505,   7,   8],
       [  7,   3,   4]])

In [66]:
b[1] = [5,6,7]

In [67]:
b

array([[505,   7,   8],
       [  5,   6,   7]])

In [80]:
b[:, 1] = [10,9]
b

array([[505,  10,   8],
       [  5,   9,   7]])

In [81]:
np.append(b, [[1,1,1]], axis = 0)  #row

array([[505,  10,   8],
       [  5,   9,   7],
       [  1,   1,   1]])

In [86]:
b = np.append(b, [[1],[1]], axis=1)

In [87]:
np.delete(b,1,axis = 1)

array([[505,   8,   1],
       [  5,   7,   1]])

In [ ]:
# Array creation function
    #np.array()
    #np.arange()
    # np.linspace()
    # np.ones()
    # np.zeros()
    # np.eye()
    # np.random.radint()