In [5]:
import numpy as np

In [2]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.arange(1,11,1.5)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [4]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
list(range(1,11,1.5))

TypeError: 'float' object cannot be interpreted as an integer

In [11]:
print(np.ones([4,5]))
print(np.zeros([4,5]))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
np.ones([4,5], dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
p = np.ones([4,5])
p

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
p.dtype

dtype('float64')

In [15]:
p.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
np.random.randint(1,100,5)

array([31, 63, 49, 43, 37])

In [17]:
np.random.randint(1,100, [3,5])

array([[69, 66,  2, 53, 53],
       [90, 34, 18, 38, 41],
       [65, 46, 23, 28, 65]])

In [19]:
np.random.seed(5000)  #fix kr deta h random value ko bhi accordin to value input eg. 5000, 198 etc.
np.random.randint(1,100, [3,5])

array([[28, 67, 98,  2, 30],
       [ 3, 15,  4, 97, 60],
       [27, 68, 47,  4, 65]])

In [22]:
r = np.random.rand(3,4) * 100
r

array([[98.03791769, 34.98358288,  4.87115115,  1.24008458],
       [35.25145846, 87.42794273, 64.26912036, 94.09038058],
       [23.44856028, 34.15686556,  2.74062666,  7.93147283]])

In [24]:
np.random.randn(3,4)   #+ve/ -ve both

array([[ 1.43541413,  0.28814703,  0.41238692, -0.53388759],
       [ 1.31369213, -0.122357  , -0.25115838,  2.16102523],
       [ 0.61623328, -1.18917849,  0.72781324,  0.59271015]])

In [25]:
import random

In [30]:
np.loadtxt('data.txt', dtype='str')     #in data, no. of columns/words should be same

array([['this', 'is', 'a', 'new', 'file'],
       ['here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [32]:
np.loadtxt('data1.txt',delimiter=',',dtype='int')

array([[45, 65, 78, 98],
       [23, 19,  3, 88],
       [ 1,  4,  5,  6]])

In [34]:
a = np.random.randint(10,1000, [3,6])
a

array([[208, 201, 387, 554, 230, 308],
       [980, 605, 357, 682, 239, 730],
       [825, 218, 286, 390, 255, 459]])

In [35]:
np.savetxt('data3.txt', a, delimiter='|', fmt='%d')

In [6]:
b = np.random.randint(10,1000, [3,6])
b

array([[181, 512, 159, 421, 476, 425],
       [869, 257, 329, 263, 728, 312],
       [285, 643, 402, 704, 519, 983]])

In [7]:
sum(sum(b))

8468

In [8]:
b.sum()

8468

In [9]:
b.sum(axis=1)  #here in this case for row, axis=1 only 

array([2174, 2758, 3536])

In [11]:
b.mean(axis=1)

array([362.33333333, 459.66666667, 589.33333333])

In [13]:
b.max(axis=1)

array([512, 869, 983])

In [14]:
b.argmax(axis=1)

array([1, 0, 5], dtype=int64)

In [15]:
b

array([[181, 512, 159, 421, 476, 425],
       [869, 257, 329, 263, 728, 312],
       [285, 643, 402, 704, 519, 983]])

In [16]:
b.argmax()

17